Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [131]:
import numpy as np

In [132]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list_1D=[1,2,3,4,5]
array_1D= np.array(list_1D)
print("The required 1D array:")
print(array_1D)
print('\n')
list_2D=[[1,2,3,4],[4,5,6,5],[8,9,10,11]]
array_2D=np.array(list_2D)
print("The required 2D array:")
print(array_2D)
print('\n')




The required 1D array:
[1 2 3 4 5]


The required 2D array:
[[ 1  2  3  4]
 [ 4  5  6  5]
 [ 8  9 10 11]]




In [133]:
# Write a NumPy function to create an array with random values of shape [3,4]
random_arr=np.random.rand(3,4)
#this creates a random array of elements within in 0-1
print(random_arr)
print('\n')
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
zeros_arr=np.zeros((3,4))
print("The required zero element array:")
print(zeros_arr)
print('\n')
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ones_arr=np.ones((3,4))
print("The required ones element array:")
print(ones_arr)
print('\n')



[[0.49311024 0.03832908 0.17768022 0.28167787]
 [0.08968735 0.50369144 0.1136955  0.13641151]
 [0.78691969 0.59291587 0.37612149 0.82090477]]


The required zero element array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The required ones element array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]




In [134]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
print("using np.arange()")
arange_arr=np.arange(2,10,3)
print(arange_arr)
print('\n')
print("using np.linspace():")
linspace_arr=np.linspace(10,30,num=11)
print(linspace_arr)
print('\n')


using np.arange()
[2 5 8]


using np.linspace():
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]




### Basic array operations
- algebraic operations
- logical operations

In [135]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [136]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print("addition of a & b:")
q=a+b
print(q)
print('\n')
print("subtraction of a & b:")
w=a-b
print(w)
print('\n')
print("algebric multiplication of a & b:")
r=np.matmul(a,b)
print(r)
print('\n')
print("division of a & b:")
j=np.linalg.det(b)
if j==0 :
    print("division is not possible")
else:
    v=np.linalg.inv(b)
    print(np.matmul(a,v))
print('\n')




addition of a & b:
[[ 7 22 26]
 [99 40 82]
 [62 56 80]]


subtraction of a & b:
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]


algebric multiplication of a & b:
[[ 984  542 1014]
 [ 430  303  480]
 [1036  552 1041]]


division of a & b:
[[-2.49247471 -0.81174439  1.58154453]
 [ 3.30150506  0.83765112 -1.68369109]
 [ 1.3002714   0.06908463 -0.32000987]]




In [137]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print("sum along axis=0:")
print(np.sum(a,axis=0))
print('\n')

# Write a NumPy function to get the sum of the array 'a' along axis=1
print("sum along axis=1:")
print(np.sum(a,axis=1))
print('\n')


sum along axis=0:
[ 6 17 14]


sum along axis=1:
[10 13 14]




In [138]:
# Write a NumPy function to reverse the array 'a'
c=np.flip(a)
print("Array after total flip:")
print(c)
print('\n')
# Write a NumPy function to reverse the array 'a' along axis=0
d=np.flip(a,axis=0)
print("Array after flip along axis=0 :")
print(d)
print('\n')
# Write a NumPy function to reverse the array 'a' along axis=1
e=np.flip(a,axis=1)
print("Array after flip along axis=1: ")
print(e)
print('\n')


Array after total flip:
[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


Array after flip along axis=0 :
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


Array after flip along axis=1: 
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]




### Sorting and concatenation
- sort arrays
- join multiple arrays


In [139]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [140]:
# Write a NumPy function to sort the array 'a'
print("array after sorting:")
print(np.sort(a))
print('\n')

# Write a NumPy function to sort the array 'a' along axis=0
print("array after sorting along axis=0:")
print(np.sort(a,axis=0))
print('\n')

# Write a NumPy function to sort the array 'a' along axis=1
print("array after sorting along axis=1:")
print(np.sort(a,axis=1))
print('\n')

# Write a NumPy function to sort the array 'a' in descending order along axis=0
print("sorting in decreasing order along axis=0")
print(-np.sort(-a,axis=0))
print('\n')



array after sorting:
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


array after sorting along axis=0:
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]


array after sorting along axis=1:
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


sorting in decreasing order along axis=0
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]




In [141]:
# Write a NumPy function to argsort the array along axis=0
print("index array after using argsort along axis=0:")
print(np.argsort(a,axis=0))
print('\n')

# Write a NumPy function to argsort the array along axis=1
print("index array after using argsort along axis=1:")
print(np.argsort(a,axis=1))
print('\n')


index array after using argsort along axis=0:
[[0 1 1]
 [2 0 2]
 [1 2 0]]


index array after using argsort along axis=1:
[[0 1 2]
 [2 1 0]
 [0 2 1]]




In [142]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print("array after concatenation:")
print(np.concatenate((a,b)))
print('\n')

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print("array after concetenation along axis=0")
print(np.concatenate((a,b),axis=0))
print('\n')

# Note: You can do the same function using stacking, discover and try that :)
print("array after stacking along axis=0:")
print(np.vstack((a,b)))
print('\n')



array after concatenation:
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


array after concetenation along axis=0
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


array after stacking along axis=0:
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]




### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [143]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [144]:
# Write a NumPy function to get the Number of dimensions
print("number of dimensions of a :",np.ndim(a))
print('\n')

# Write a NumPy function to get the Shape of the array
print("Shape of a:",a.shape)
print('\n')

# Write a NumPy function to get the Size of the array
print("size of a :",a.size)
print('\n')

number of dimensions of a : 2


Shape of a: (3, 3)


size of a : 9




In [146]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print("array after reshaping :")
print(a.reshape(1,9))
print('\n')


array after reshaping :
[[4 6 8 9 3 1 1 8 5]]




In [147]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print("adding an axis at the starting :")
l=a[np.newaxis,:,:]
print(l)
print('\n')
print("shape after new axis:",l.shape)
print('\n')
print("adding an axis at the middle:")
print(a[:,np.newaxis,:])
print("shape after new axis:",a[:,np.newaxis,:].shape)




adding an axis at the starting :
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


shape after new axis: (1, 3, 3)


adding an axis at the middle:
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
shape after new axis: (3, 1, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [148]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [149]:
# Write a NumPy function to index and slice NumPy arrays similar to Python list
# Show all three - indexing by a integer, indexing by a tuple, using range
print("indexing using integer:")
print("the array of a[1]:",a[1])
print('\n')
print("indexing using tuple:")
print("the array of a[(1,2)]:",a[(1,2)])
print('\n')
print("indexing using range:")
print("the array of a[0:2,1:2]:",a[0:2,1:2])
print('\n')


indexing using integer:
the array of a[1]: [0 3 1]


indexing using tuple:
the array of a[(1,2)]: 1


indexing using range:
the array of a[0:2,1:2]: [[6]
 [3]]




In [150]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
print('\n')

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4)&(a%2==0)])
print('\n')


[6 8 5]


[6 8]




### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [151]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [152]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
m=a.copy()
print(m+1)
print('\n')


[[5 7 1]
 [1 4 2]
 [2 9 6]]




## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [153]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
import ssl
import pandas as pd
from urllib.request import urlopen


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
iris_2d = np.genfromtxt(data, delimiter=',', dtype = 'float', usecols=(0,1,2,3), encoding='utf-8')

#### Basic Data Analysis

In [154]:
# Write a Pandas function to drop rows that contain a missing value.
df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df_clean=df.dropna()


In [155]:
# Write a Pandas function to find the correlation between the first two columns.
correlation = df['sepal_length'].corr(df['sepal_width'])

In [156]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
col3_mean = df['petal_length'].mean()
col3_median = df['petal_length'].median()
col3_std = df['petal_length'].std()
print("the required mean:",col3_mean)
print("the required median:",col3_median)
print("the required standard deviation:",col3_std)
print('\n')

the required mean: 3.758666666666666
the required median: 4.35
the required standard deviation: 1.7644204199522626




In [157]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df['volume'] = np.pi * df['petal_length'] * (df['sepal_length'] ** 2) #using direct pandas function 


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [158]:
x = np.arange(4, dtype=np.int64)
f=np.full_like(x,1)
h=np.ones_like(x)
print(h)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [159]:
x=np.array([1,2,3,4,5,6,7,8,9])
n_1=x[0:4]
n_2=x[4:6]
n_3=x[6:9]
print("the first part:",n_1)
print("the second part:",n_2)
print("the third part:",n_3)
print('\n')

the first part: [1 2 3 4]
the second part: [5 6]
the third part: [7 8 9]




Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [160]:
x=np.random.randint(0,10,size=(2,5))
print("the min value:",np.min(x))
print("the min index:",np.argmin(x))
print("the max value:",np.max(x))
print("the max index:",np.argmax(x))

the min value: 0
the min index: 0
the max value: 9
the max index: 1


### Pandas

Run the following load command and solve the following questions

In [161]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
import ssl
import pandas as pd
from urllib.request import urlopen
from io import StringIO

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
text = data.read().decode('utf-8')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_df = pd.read_csv(StringIO(text),header=None,names=names)

Q4 Write a Pandas function to find the count of unique species.

In [162]:
unique_species_count = iris_df['species'].nunique()
print("the unique species count is :",unique_species_count)
print('\n')

the unique species count is : 3




# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [163]:

petal_lengths = iris_2d[:, 2]
binned_petals = pd.cut(
    petal_lengths, 
    bins=[0, 3, 5, np.inf], 
    labels=['small', 'medium', 'large'], 
)
print(binned_petals)
print('\n')

['small', 'small', 'small', 'small', 'small', ..., 'large', 'medium', 'large', 'large', 'large']
Length: 150
Categories (3, object): ['small' < 'medium' < 'large']




Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [164]:
most_frequent = pd.Series(iris_2d[:, 2]).mode()[0]
print("The most frequent petal length is:", most_frequent)
print('\n')

The most frequent petal length is: 1.5


